name: 'Continuous Integration'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check-dist:
    name: Check dist/ directory
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@967035ce963867fb956a309c9b67512314bc7c1f
    with:
      node-version: "24.x"
  test:
    name: Test
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@967035ce963867fb956a309c9b67512314bc7c1f
    with:
      node-version: "24.x"
